### PR TITLE
Implementing text language Translation

### PR DESCRIPTION
**Pull request by ConradKash**

### CODE REVIEW

**Comment by ConradKash** [comment]
@cmplx-xyttmt  the pytest is failing because it cant cinnect to higging_face But basically am done. I will comment out those tests

**Comment by ConradKash** [comment]
I had an issue with the test of which the last 2 were about the version of python and sklearn. Please Review

**Comment by cmplx-xyttmt** [comment]
> @cmplx-xyttmt the pytest is failing because it cant cinnect to higging_face But basically am done. I will comment out those tests

Don't comment them out. There's a way of accessing environment variables on Github. A better solution is to us e pytest mocking which you can read about here: https://pytest-with-eric.com/pytest-advanced/pytest-mocking/

**Review by Ignatius-K — APPROVED** [review]
It seems good

**Review by cmplx-xyttmt — APPROVED** [review]
Merging, but some with some issues to note:
- Use `response.json()` instead of `response.text` to extract the translation from the response.
- No need for `time.sleep` since you're already using exponential backoff.

**Pull request merged**
